/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Class;

/**
 * class untuk menterjemahkan bahasa
 * @author Muhammad Farchan Al Rahman (G1A020008)
 */
public class EngInd extends javax.swing.JFrame {

    /**
     * membuat tampilan aplikasi
     */
    public EngInd() {
        initComponents();
    }
    /** 
     * method yang digunakan untuk
     * menerapkan algoritma
     * binary search
     * @author Muhammad Farchan Al Rahman (G1A020008)
     */
    static int binarySearch(String[] english, String word){
	int first = 0, last = english.length - 1; //mengatur awal dan akhir array
            while (first <= last) { //membuat perulangan dengan kondisi nilai dari first sampai last
		int mid = first + (last - first) / 2; //mencari nilai tengah array

		int res = word.compareTo(english[mid]); //mendapatakan hasil dari nilai tengah array

		// Check if res terdapat di tengah
		if (res == 0)
                    return mid;

		// jika res lebih besar, abaikan bagian kiri dari nilai tengah
		if (res > 0)
                    first = mid + 1;

		// jika res lebih kecil, abaikan bagian kanan dari nilai tengah
		else
                    last = mid - 1;
		}

            return -1; //kembalikan nilai -1 jika tidak ditemukan
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textIndonesia = new javax.swing.JTextField();
        textEnglish = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnTranslate = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        textIndonesia.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        textIndonesia.setBorder(null);

        textEnglish.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        textEnglish.setBorder(null);

        btnBack.setBorder(null);
        btnBack.setContentAreaFilled(false);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnRefresh.setBorder(null);
        btnRefresh.setContentAreaFilled(false);
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnTranslate.setBorder(null);
        btnTranslate.setContentAreaFilled(false);
        btnTranslate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTranslateActionPerformed(evt);
            }
        });

        btnExit.setBorder(null);
        btnExit.setContentAreaFilled(false);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/EngInd.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1131, 1131, 1131)
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textEnglish, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(279, 279, 279)
                        .addComponent(btnTranslate, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addComponent(textIndonesia, javax.swing.GroupLayout.PREFERRED_SIZE, 594, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lblBackground)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(142, 142, 142)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textEnglish, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(btnTranslate, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(384, 384, 384)
                                .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(textIndonesia, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addComponent(lblBackground)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        textEnglish.setText(null);
        textIndonesia.setText(null);
         //button untuk mengosongkan text area
        textIndonesia.setEditable(false);
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnTranslateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTranslateActionPerformed
        /**
        * @author Muhammad Farchan Al Rahman (G1A020008)
        * Action event pada button translate yang digunakan untuk
        * menemukan data yang dicari
        */
        String[] english = {"father", "sister", "brother", "grandmother", "grandfather", "cat", "dog", "duck", "horse", "bird", 
            "snake", "squirrel", "goats", "cows", "phone", "broom", "rake", "kick", "head", "throw", "love", "dirty", "nostalgic",
            "dear", "always", "usually", "before", "forget", "rice", "finger", "earth", "vegetable", "egg", "salt", "bread", 
            "impossible", "confident", "helpful", "young", "kind", "cool", "hot", "pretty", "lazy", "tall", "short", "ugly", 
            "soft", "little", "angry", "happy", "smart", "world", "information", "map", "art", "people", "computer", "cut", "meat", 
            "system", "problem", "television", "law", "knowledge", "ability", "nature", "thing", "exam", "player", "story", "movie", 
            "camera", "paper", "news", "writing", "month", "child", "different", "goal", "truth", "university", "definitely", 
            "currently", "equipment", "organization" ,"history", "way","art","available", "basic","dramatic"," eastren", "entire", 
            "environmental","famous","medical","mad","nervous", "one","two", "three", "four", "five", "six", "seven", "eight", 
            "nine" , "ten","add","adjust","admire","admit","adopt","afford","allow","announce", "apply","approach","approve",
            "argue","assume","borrow","bring","build","calculate","celebrate","come","commit","enter","establish","examine","exist",
            "expand","get","grow","happen","has","hear","know","learn","lose","apple","avocado","banana","blueberry","grape","guava",
            "lemon","lychee","mango","melon","orange","strawberry","watermelon", "office", "work", "pen", "pencil", "ruler", "eraser",
            "coat", "bag", "company", "door", "wardrobe", "drawer", "chair "," sofa "," president "," commander "," lieutenant ",
            " corporal "," captain "," soldier "," cadet "," student "," student "," teacher "," lecturer ", "college", "school", 
            "small", "big", "left", "right", "up", "down", "side", "middle", "device", "hardware", " software "," heart "," eyes ",
            " nose "," head "," ears "," hair "," eyebrows "," mouth "," teeth "," tongue "," chin "," neck "," chest ",
            " shoulder "," hand "," arm "," finger "," thumb "," index finger "," ring finger "," middle finger "," little finger ",
            " stomach ", "navel", "groin", "thigh", "knee", "foot", "foot", "brain", "skull", "throat", "esophagus", "heart", 
            "intestine", " small intestine "," large intestine "," lungs "," heart "," veins "," arterial blood vessels "," blood ",
            " red blood cells "," white blood cells "," pigments " , "photosynthesis", "radiation", "mosque","church","temple",
            "shrine","pagoda","synagogue","boy","girl","bike","motorcycle","car","eyeglasses","grass","buffalo","policeman",
            "policewoman","water","fire","wind","soil","earthquake","box","floor","help","sorry","wheels","principal","zoo",
            "zone","chain","butterfly","locust","dragonfly","pig","dog","doggy","piggy"
        };
            
        String[] indo = {"ayah", "saudara perempuan", "saudara laki-laki", "nenek", "kakek", "kucing", "anjing", "bebek", "kuda", "burung",
            "ular", "tupai", "kambing", "sapi", "telepon", "sapu", "menyapu", "tendang", "kepala", "lempar", "cinta", "kotor", "nostalgia ",
            "sayang", "selalu", "biasanya", "sebelum", "lupa", "nasi", "jari", "bumi", "sayur", "telur", "garam", "roti",
            "tidak mungkin", "percaya diri", "membantu", "muda", "baik hati", "keren", "panas", "cantik", "malas", "tinggi", "pendek", "jelek",
            "lembut", "kecil", "marah", "senang", "pintar", "dunia", "informasi", "peta", "seni", "orang", "komputer", "potong", "daging ",
            "sistem", "masalah", "televisi", "hukum", "pengetahuan", "kemampuan", "sifat", "benda", "ujian", "pemain", "cerita", "film",
            "kamera", "kertas", "berita", "tulisan", "bulan", "anak", "berbeda", "tujuan", "kebenaran", "universitas", "pasti",
            "saat ini", "peralatan", "organisasi", "sejarah", "cara", "seni", "tersedia", "dasar", "dramatis", "timur", "keseluruhan",
            "lingkungan", "terkenal", "medis", "gila", "gugup", "satu", "dua", "tiga", "empat", "lima", "enam", "tujuh", "delapan ",
            "sembilan", "sepuluh", "tambah", "sesuaikan", "kagumi", "akui", "adopsi", "beli", "izinkan", "umumkan", "terapkan", "pendekatan", 
            "setujui ","berdebat", "berasumsi", "meminjam", "membawa", "membangun", "menghitung", "merayakan", "datang", "berkomitmen", "masuk", 
            "membangun", "memeriksa", "ada ","memperluas", "mendapatkan", "tumbuh", "terjadi", "memiliki", "mendengar", "tahu", "belajar", "kalah", 
            "apel", "alpukat", "pisang", "blueberry "," anggur "," jambu biji ","lemon", "leci", "mangga", "melon", "jeruk", "stroberi", "semangka", 
            "kantor", "kantor", "pena", "pensil", "penggaris", "penghapus ","mantel", "tas", "kompi", "pintu", "lemari", "laci", "kursi", "sofa", 
            "presiden", "komandan", "letnan","kopral", "kapten", "prajurit", "kadet", "mahasiswa", "mahasiswa", "guru", "dosen", "perguruan tinggi", "sekolah",
            "kecil", "besar", "kiri", "kanan", "atas", "bawah", "samping", "tengah", "perangkat", "perangkat keras", "perangkat lunak", "hati", "mata ",
            "hidung", "kepala", "telinga", "rambut", "alis", "mulut", "gigi", "lidah", "dagu", "leher", "dada",
            "bahu", "tangan", "lengan", "jari", "ibu jari", "jari telunjuk", "jari manis", "jari tengah", "jari kelingking",
            "perut", "pusar", "selangkangan", "paha", "lutut", "kaki", "kaki", "otak", "tengkorak", "tenggorokan", "kerongkongan", "jantung",
            "usus", "usus kecil", "usus besar", "paru-paru", "jantung", "vena", "pembuluh darah arteri", "darah",
            "sel darah merah", "sel darah putih", "pigmen", "fotosintesis", "radiasi", "masjid", "gereja", "kuil",
            "kuil", "pagoda", "sinagog", "anak laki-laki", "gadis", "sepeda", "sepeda motor", "mobil", "kacamata", "rumput", "kerbau", "polisi",
            "polisi wanita", "air", "api", "angin", "tanah", "gempa bumi", "kotak", "lantai", "bantuan", "maaf", "roda", "kepala sekolah", "kebun binatang ",
            "zona", "rantai", "kupu-kupu", "belalang", "capung", "babi", "anjing", "anjing", "babi"
        };
        /**
         * sorting digunakan pada algoritma binary search karena harus mencaari 
         * nilai tengah dari array
         */
        for(int i = 0; i<english.length-1; i++){  
            for (int j = i+1; j<english.length; j++){
                if(english[i].compareTo(english[j])>0){  
                    //swapping array elements  
                    /**
                     * dimulai dari menyimpan element array yang dimulai dari nol
                     * lalu dibandingkan dengan elemen padda array selanjutnya
                     * lalu disimpan kembali pada temporary
                     */
                    String tempEnglish = english[i];
                    english[i] = english[j];  
                    english[j] = tempEnglish;
                    
                    String tempIndo = indo[j];
                    indo[j]=indo[i];
                    indo[i]=tempIndo;
                }  
            }  
         }  // method yang digunakan untuk mengurutkan kosakata A-Z berdasarkan kosakata Inggris
        String englishText = textEnglish.getText();
        String word = englishText.toLowerCase();
        int result = binarySearch(english, word);
        if (result == -1) //jika nilai tidak ada pada array
            textIndonesia.setText("Kata Tidak Tersedia");
        else //jika nilai ditemukan
            textIndonesia.setText( indo[result]);
        //mencari kata dengan binary search
         textIndonesia.setEditable(false);
    }//GEN-LAST:event_btnTranslateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EngInd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EngInd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EngInd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EngInd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EngInd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnTranslate;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JTextField textEnglish;
    private javax.swing.JTextField textIndonesia;
    // End of variables declaration//GEN-END:variables
}
